### ISSUE TITLE
Stuck at "Rest service started", and BBS never loads over Telnet

### ISSUE THREAD

**Issue by squintgit** [iniquitybbs/iniquity#13]
So I've tried installing this reimagined version of Iniquity on two different Macs, one running macOS Mojave, and the other macOS Catalina, and every time I get to the end of the installation process and run "iniquity", I get "Rest service started". 

<img width="561" alt="iniq" src="https://user-images.githubusercontent.com/11663794/78307717-29d36a80-750c-11ea-957c-8c5a89be5959.png">

Eventually I get "iniquity - Periodic timed event example..."

Then if I try to connect via Telnet, I get "iniquity - Someone connected to the system.."

But the software never loads:

<img width="752" alt="Screen Shot 2020-04-02 at 6 09 05 PM" src="https://user-images.githubusercontent.com/11663794/78308099-268cae80-750d-11ea-9811-baeb1c5d6276.png">

**Comment by squintr** [comment]
I tried doing sudo to make sure I had proper permissions and had similar results

<img width="2042" alt="Screen Shot 2020-04-03 at 6 35 34 PM" src="https://user-images.githubusercontent.com/11663794/78412804-581f7b80-75da-11ea-9f6b-69d8ab306fed.png">

**Comment by ispyhumanfly** [comment]
So... honestly, that's as far as the version that's available on rub gems is. The source code that's here on git is likely broken as well as I'm midway through finishing the iqruntime prototype environment. The last couple of weeks I've had some time to make progress on that so lately I've been feeling energized to try and get us to alpha. 

I'm so sorry for any confusion as to the readiness of iq3 but I can assure you I'm eager to get this board into peoples hands...

**Comment by squintgit** [comment]
Ahh ok, thought I was doing something wrong. Really excited about this project.

**Comment by ispyhumanfly** [comment]
> Ahh ok, thought I was doing something wrong. Really excited about this project.

Hey man I'm glad to hear it! It motivates me to get it to an alpha.
