### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by squintgit** [iniquitybbs/iniquity#14]
https://github.com/iniquitybbs/iniquity

links to:

https://www.rubydoc.info/github/iniquitybbs/iniquity/master

which results in:

RubyDoc.info YARD Documentation Server
We Couldn't Find That Page

Sorry, but we couldn't find the page /github/iniquitybbs/iniquity/master in the iniquitybbs/iniquity GitHub repository. Are you sure that class, method, or file exists?

<img width="722" alt="Screen Shot 2020-04-03 at 6 37 04 PM" src="https://user-images.githubusercontent.com/11663794/78412757-28707380-75da-11ea-972f-4bab330760b7.png">

**Comment by ispyhumanfly** [comment]
Thanks, squint. I'm working to migrate this away from the hosted rdoc solution you mentioned here. It's been broken for some time admittedly. Thanks for reporting this.

**Comment by squintgit** [comment]
Thanks sorry for all the individual bugs on the docs, sounds like those weren't needed. Should I close them?

**Comment by ispyhumanfly** [comment]
Hey don't even sweat it. Also, I read your email. If you're down to help. I could use it... motivation haha.
