### ISSUE TITLE
OMG ... that reminds me.....

### ISSUE THREAD

**Issue by michabbb** [iniquitybbs/iniquity#3]
sorry for posting here... i had this running so many years ago... the original... in times nobody heard of "internet", amazing ! ;-) 

i have to ask (maybe) a stupid question: what is this project about ? can you give me some use-cases here ??

THX!

**Comment by ispyhumanfly** [comment]
Hi @michabbb , thanks for posting a question here. No such thing as a stupid question in my view. Sorry I've had to focus on work the past several months; I only just noticed the question. Well, the README.md in the root directory as well as the README.md in the docs/ directory have most of the notes for now. We want to make this the Iniquity BBS that always was and should have become. Sadly I feel that Iniquity came too late in the game to really see development beyond Alpha. The internet all but killed the BBS around the time that Mike Fricker authored the original version. Yet it remains iconic, and, is the inspiration for this new version and complete re-write.

**Comment by michabbb** [comment]
Okay, I wasn't aware that bbs still exists in these times or someone knows howto use them 😊 in the past you needed a phone number, so how is it today, am ip? (sorry, didn't read the docu if it's explained there).

**Comment by ispyhumanfly** [comment]
@michabbb there is an entire world out there filled with modern BBSs. :) www.synchronet.net, www.mysticbbs.net, and the enigma bbs software packages are actively developed and used. I'd say the BBS scene is still small, but, nearly 500 boards around the world actively exist with a few thousand people still using them.

**Comment by michabbb** [comment]
Crazy, I wasn't aware of the fact that all this still exists, thanks for letting me know 😊
