### ISSUE TITLE
Iniquitybbs.org doesn't work

### ISSUE THREAD

**Issue by UnaClocker** [iniquitybbs/iniquity#6]
Maybe it's just down right now, but the website doesn't load.

**Comment by ispyhumanfly** [comment]
Yeah, I fell off the deep end a little. I'm getting it back up. Thanks @UnaClocker !

**Comment by squintr** [comment]
Any update here?

**Comment by ispyhumanfly** [comment]
Yes, I'm working to bring the site back up now. Very sorry for the delays gents.

**Comment by ispyhumanfly** [comment]
[This is also resolved.](http://iniquitybbs.org)
