### ISSUE TITLE
Documentation link doesn't work

### ISSUE THREAD

**Issue by UnaClocker** [iniquitybbs/iniquity#7]
The link to the documentation doesn't work.

**Comment by ispyhumanfly** [comment]
Yes, I will work to resolve this. @UnaClocker

**Comment by squintr** [comment]
Any update on this?

**Comment by ispyhumanfly** [comment]
Yes. The documentation is transitioning from the hosted rdoc solution it's on now. I'm assigning this to myself and will work to get this back online.

**Comment by ispyhumanfly** [comment]
An update. TypeDoc is going to place Rdoc on this project soon.

**Comment by ispyhumanfly** [comment]
[This is finally resolved.](https://iniquitybbs.org/modules/Iniquity.html) :)
